# -*- coding: utf-8 -*-
"""average_long_sen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aCuNDNio5ON-AyJUdmw4gPe24Gs5hLaD
"""

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

!ls drive/MyDrive

!find drive/MyDrive

!ls drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/record_kids_data/data.zip

!unzip drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/record_kids_data/data.zip

import zipfile
import os
import pandas as pd
from openpyxl import Workbook

# Path to the ZIP file
zip_path = 'drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/record_kids_data/data.zip'

# List to store average sentence length data
avg_sentence_lengths = []

# Open the ZIP file
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    # Iterate through each file in the ZIP
    for file_info in zip_ref.infolist():
        # Check if the file is a text file
        if file_info.filename.endswith('.cha'):
            # Check if the filename contains the desired words
            if 'finished' in file_info.filename and 'Braunwald' in file_info.filename:
                # Read the content of the file
                with zip_ref.open(file_info.filename) as file:
                    file_contents = file.read().decode('utf-8')
                    # Split the file content into sentences (each line is a sentence)
                    sentences = file_contents.split('\n')
                    # Calculate the average sentence length
                    sentence_lengths = [len(sentence.split()) for sentence in sentences]
                    avg_sentence_length = sum(sentence_lengths) / len(sentence_lengths)
                    # Add the average sentence length to the list
                    avg_sentence_lengths.append((file_info.filename, avg_sentence_length))

# Create a DataFrame from the list
data_df = pd.DataFrame(avg_sentence_lengths, columns=['filename', 'avg_sentence_length'])

# Create an Excel file
wb = Workbook()
ws = wb.active

# Column headers
ws.append(['Filename', 'Avg Sentence Length'])

# Add data to the Excel sheet
for row in avg_sentence_lengths:
    ws.append(row)

# Save the Excel file
excel_file_path = 'drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/avg_sentence_lengths.xlsx'
wb.save(excel_file_path)

print("Excel file created successfully.")

# Read the data from the Excel file
data_df = pd.read_excel('drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/long_average_sen/avg_sentence_lengths_Braunwald.xlsx')

# Create a scatter plot
plt.figure(figsize=(10, 6))
plt.scatter(data_df['age'], data_df['Avg Sentence Length'], color='blue', alpha=0.5)
plt.title('Braunwald: Avg Sentence Length vs. Age')
plt.xlabel('Age')
plt.ylabel('Avg Sentence Length')
plt.grid(True)
plt.show()
