# -*- coding: utf-8 -*-
"""average_long_sen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aCuNDNio5ON-AyJUdmw4gPe24Gs5hLaD
"""

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

!ls drive/MyDrive

!find drive/MyDrive

!ls drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/record_kids_data/data.zip

!unzip drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/record_kids_data/data.zip

import zipfile
import os
import pandas as pd
from openpyxl import Workbook

# נתיב לקובץ ZIP
zip_path = 'drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/record_kids_data/data.zip'

# רשימה לשמירת נתוני אורך משפט ממוצע
avg_sentence_lengths = []

# פתח את קובץ הZIP
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    # עבור על כל קובץ בתוך הZIP
    for file_info in zip_ref.infolist():
        # בדוק אם הקובץ הוא קובץ טקסט
        if file_info.filename.endswith('.cha'):
            # בדוק אם השם של הקובץ מכיל את המילים המבוקשות
            if 'finished' in file_info.filename and 'Braunwald' in file_info.filename:
                # קרא את תוכן הקובץ
                with zip_ref.open(file_info.filename) as file:
                    file_contents = file.read().decode('utf-8')
                    # חלק את תוכן הקובץ למשפטים (כל שורה היא משפט)
                    sentences = file_contents.split('\n')
                    # חשב את אורך המשפט הממוצע
                    sentence_lengths = [len(sentence.split()) for sentence in sentences]
                    avg_sentence_length = sum(sentence_lengths) / len(sentence_lengths)
                    # הוסף את אורך המשפט הממוצע לרשימה
                    avg_sentence_lengths.append((file_info.filename, avg_sentence_length))

# יצירת DataFrame מהרשימה
data_df = pd.DataFrame(avg_sentence_lengths, columns=['filename', 'avg_sentence_length'])

# יצירת קובץ Excel
wb = Workbook()
ws = wb.active

# כותרות העמודות
ws.append(['Filename', 'Avg Sentence Length'])

# הוספת הנתונים לגיליון אקסל
for row in avg_sentence_lengths:
    ws.append(row)

# שמירת הקובץ Excel
#excel_file_path = 'avg_sentence_lengths.xlsx'
excel_file_path = 'drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/avg_sentence_lengths.xlsx'


wb.save(excel_file_path)

print("Excel file created successfully.")

# הורדת הקובץ Excel
from google.colab import files
#files.download(excel_file_path)

import pandas as pd
import matplotlib.pyplot as plt

# קריאת הנתונים מקובץ ה-Excel
data_df = pd.read_excel('drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/long_average_sen/avg_sentence_lengths_Braunwald.xlsx')

# יצירת גרף scatter
plt.figure(figsize=(10, 6))
plt.scatter(data_df['age'], data_df['Avg Sentence Length'], color='blue', alpha=0.5)
plt.title('Braunwald: Avg Sentence Length vs. Age')
plt.xlabel('Age')
plt.ylabel('Avg Sentence Length')
plt.grid(True)
plt.show()

import zipfile
import os
import pandas as pd
from openpyxl import Workbook

# נתיב לקובץ ZIP
zip_path = 'drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/record_kids_data/data.zip'

# רשימה לשמירת נתוני אורך משפט ממוצע
avg_sentence_lengths = []

# פתח את קובץ הZIP
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    # עבור על כל קובץ בתוך הZIP
    for file_info in zip_ref.infolist():
        # בדוק אם הקובץ הוא קובץ טקסט
        #if file_info.filename.endswith('.cha'):
            # בדוק אם השם של הקובץ מכיל את המילים המבוקשות
            if 'finished' in file_info.filename and 'Brown/Sarah' in file_info.filename:
                # קרא את תוכן הקובץ
                with zip_ref.open(file_info.filename) as file:
                    file_contents = file.read().decode('utf-8')
                    # חלק את תוכן הקובץ למשפטים (כל שורה היא משפט)
                    sentences = file_contents.split('\n')
                    # חשב את אורך המשפט הממוצע
                    sentence_lengths = [len(sentence.split()) for sentence in sentences]
                    avg_sentence_length = sum(sentence_lengths) / len(sentence_lengths)
                    # הוסף את אורך המשפט הממוצע לרשימה
                    avg_sentence_lengths.append((file_info.filename, avg_sentence_length))

# יצירת DataFrame מהרשימה
data_df = pd.DataFrame(avg_sentence_lengths, columns=['filename', 'avg_sentence_length'])

# יצירת קובץ Excel
wb = Workbook()
ws = wb.active

# כותרות העמודות
ws.append(['Filename', 'Avg Sentence Length'])

# הוספת הנתונים לגיליון אקסל
for row in avg_sentence_lengths:
    ws.append(row)

# שמירת הקובץ Excel
#excel_file_path = 'avg_sentence_lengths.xlsx'
excel_file_path = 'drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/avg_sentence_lengths.xlsx'


wb.save(excel_file_path)

print("Excel file created successfully.")

# הורדת הקובץ Excel
from google.colab import files
#files.download(excel_file_path)

import pandas as pd
import matplotlib.pyplot as plt

# קריאת הנתונים מקובץ ה-Excel
data_df = pd.read_excel('drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/long_average_sen/avg_sentence_lengths_sarah.xlsx')

# יצירת גרף scatter
plt.figure(figsize=(10, 6))
plt.scatter(data_df['age'], data_df['Avg Sentence Length'], color='blue', alpha=0.5)
plt.title('Sarah: Avg Sentence Length vs. Age')
plt.xlabel('Age')
plt.ylabel('Avg Sentence Length')
plt.grid(True)
plt.show()

import zipfile
import os
import pandas as pd
from openpyxl import Workbook

# נתיב לקובץ ZIP
zip_path = 'drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/record_kids_data/data.zip'

# רשימה לשמירת נתוני אורך משפט ממוצע
avg_sentence_lengths = []

# פתח את קובץ הZIP
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    # עבור על כל קובץ בתוך הZIP
    for file_info in zip_ref.infolist():
        # בדוק אם הקובץ הוא קובץ טקסט
        #if file_info.filename.endswith('.cha'):
            # בדוק אם השם של הקובץ מכיל את המילים המבוקשות
            if 'finished' in file_info.filename and 'Brown/Adam' in file_info.filename:
                # קרא את תוכן הקובץ
                with zip_ref.open(file_info.filename) as file:
                    file_contents = file.read().decode('utf-8')
                    # חלק את תוכן הקובץ למשפטים (כל שורה היא משפט)
                    sentences = file_contents.split('\n')
                    # חשב את אורך המשפט הממוצע
                    sentence_lengths = [len(sentence.split()) for sentence in sentences]
                    avg_sentence_length = sum(sentence_lengths) / len(sentence_lengths)
                    # הוסף את אורך המשפט הממוצע לרשימה
                    avg_sentence_lengths.append((file_info.filename, avg_sentence_length))

# יצירת DataFrame מהרשימה
data_df = pd.DataFrame(avg_sentence_lengths, columns=['filename', 'avg_sentence_length'])

# יצירת קובץ Excel
wb = Workbook()
ws = wb.active

# כותרות העמודות
ws.append(['Filename', 'Avg Sentence Length'])

# הוספת הנתונים לגיליון אקסל
for row in avg_sentence_lengths:
    ws.append(row)

# שמירת הקובץ Excel
#excel_file_path = 'avg_sentence_lengths.xlsx'
excel_file_path = 'drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/avg_sentence_lengths.xlsx'


wb.save(excel_file_path)

print("Excel file created successfully.")

# הורדת הקובץ Excel
from google.colab import files
#files.download(excel_file_path)

import pandas as pd
import matplotlib.pyplot as plt

# קריאת הנתונים מקובץ ה-Excel
data_df = pd.read_excel('drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/long_average_sen/avg_sentence_lengths_Adam.xlsx')

# יצירת גרף scatter
plt.figure(figsize=(10, 6))
plt.scatter(data_df['age'], data_df['Avg Sentence Length'], color='blue', alpha=0.5)
plt.title('Adam: Avg Sentence Length vs. Age')
plt.xlabel('Age')
plt.ylabel('Avg Sentence Length')
plt.grid(True)
plt.show()

import zipfile
import os
import pandas as pd
from openpyxl import Workbook

# נתיב לקובץ ZIP
zip_path = 'drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/record_kids_data/data.zip'

# רשימה לשמירת נתוני אורך משפט ממוצע
avg_sentence_lengths = []

# פתח את קובץ הZIP
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    # עבור על כל קובץ בתוך הZIP
    for file_info in zip_ref.infolist():
        # בדוק אם הקובץ הוא קובץ טקסט
        #if file_info.filename.endswith('.cha'):
            # בדוק אם השם של הקובץ מכיל את המילים המבוקשות
            if 'finished' in file_info.filename and 'Brown/Eve' in file_info.filename:
                # קרא את תוכן הקובץ
                with zip_ref.open(file_info.filename) as file:
                    file_contents = file.read().decode('utf-8')
                    # חלק את תוכן הקובץ למשפטים (כל שורה היא משפט)
                    sentences = file_contents.split('\n')
                    # חשב את אורך המשפט הממוצע
                    sentence_lengths = [len(sentence.split()) for sentence in sentences]
                    avg_sentence_length = sum(sentence_lengths) / len(sentence_lengths)
                    # הוסף את אורך המשפט הממוצע לרשימה
                    avg_sentence_lengths.append((file_info.filename, avg_sentence_length))

# יצירת DataFrame מהרשימה
data_df = pd.DataFrame(avg_sentence_lengths, columns=['filename', 'avg_sentence_length'])

# יצירת קובץ Excel
wb = Workbook()
ws = wb.active

# כותרות העמודות
ws.append(['Filename', 'Avg Sentence Length'])

# הוספת הנתונים לגיליון אקסל
for row in avg_sentence_lengths:
    ws.append(row)

# שמירת הקובץ Excel
#excel_file_path = 'avg_sentence_lengths.xlsx'
excel_file_path = 'drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/avg_sentence_lengths.xlsx'


wb.save(excel_file_path)

print("Excel file created successfully.")

# הורדת הקובץ Excel
from google.colab import files
#files.download(excel_file_path)

import pandas as pd
import matplotlib.pyplot as plt

# קריאת הנתונים מקובץ ה-Excel
data_df = pd.read_excel('drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/long_average_sen/avg_sentence_lengths_Eve.xlsx')

# יצירת גרף scatter
plt.figure(figsize=(10, 6))
plt.scatter(data_df['age'], data_df['Avg Sentence Length'], color='blue', alpha=0.5)
plt.title('Eve: Avg Sentence Length vs. Age')
plt.xlabel('Age')
plt.ylabel('Avg Sentence Length')
plt.grid(True)
plt.show()

import zipfile
import os
import pandas as pd
from openpyxl import Workbook

# נתיב לקובץ ZIP
zip_path = 'drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/record_kids_data/data.zip'

# רשימה לשמירת נתוני אורך משפט ממוצע
avg_sentence_lengths = []

# פתח את קובץ הZIP
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    # עבור על כל קובץ בתוך הZIP
    for file_info in zip_ref.infolist():
        # בדוק אם הקובץ הוא קובץ טקסט
        #if file_info.filename.endswith('.cha'):
            # בדוק אם השם של הקובץ מכיל את המילים המבוקשות
            if 'finished' in file_info.filename and 'ComptonPater/Julia' in file_info.filename:
                # קרא את תוכן הקובץ
                with zip_ref.open(file_info.filename) as file:
                    file_contents = file.read().decode('utf-8')
                    # חלק את תוכן הקובץ למשפטים (כל שורה היא משפט)
                    sentences = file_contents.split('\n')
                    # חשב את אורך המשפט הממוצע
                    sentence_lengths = [len(sentence.split()) for sentence in sentences]
                    avg_sentence_length = sum(sentence_lengths) / len(sentence_lengths)
                    # הוסף את אורך המשפט הממוצע לרשימה
                    avg_sentence_lengths.append((file_info.filename, avg_sentence_length))

# יצירת DataFrame מהרשימה
data_df = pd.DataFrame(avg_sentence_lengths, columns=['filename', 'avg_sentence_length'])

# יצירת קובץ Excel
wb = Workbook()
ws = wb.active

# כותרות העמודות
ws.append(['Filename', 'Avg Sentence Length'])

# הוספת הנתונים לגיליון אקסל
for row in avg_sentence_lengths:
    ws.append(row)

# שמירת הקובץ Excel
#excel_file_path = 'avg_sentence_lengths.xlsx'
excel_file_path = 'drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/avg_sentence_lengths.xlsx'


wb.save(excel_file_path)

print("Excel file created successfully.")

# הורדת הקובץ Excel
from google.colab import files
#files.download(excel_file_path)

import pandas as pd
import matplotlib.pyplot as plt

# קריאת הנתונים מקובץ ה-Excel
data_df = pd.read_excel('drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/long_average_sen/avg_sentence_lengths_Julia.xlsx')

# יצירת גרף scatter
plt.figure(figsize=(10, 6))
plt.scatter(data_df['age'], data_df['Avg Sentence Length'], color='blue', alpha=0.5)
plt.title('Julia: Avg Sentence Length vs. Age')
plt.xlabel('Age')
plt.ylabel('Avg Sentence Length')
plt.grid(True)
plt.show()

import zipfile
import os
import pandas as pd
from openpyxl import Workbook

# נתיב לקובץ ZIP
zip_path = 'drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/record_kids_data/data.zip'

# רשימה לשמירת נתוני אורך משפט ממוצע
avg_sentence_lengths = []

# פתח את קובץ הZIP
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    # עבור על כל קובץ בתוך הZIP
    for file_info in zip_ref.infolist():
        # בדוק אם הקובץ הוא קובץ טקסט
        #if file_info.filename.endswith('.cha'):
            # בדוק אם השם של הקובץ מכיל את המילים המבוקשות
            if 'finished' in file_info.filename and 'ComptonPater/Sean' in file_info.filename:
                # קרא את תוכן הקובץ
                with zip_ref.open(file_info.filename) as file:
                    file_contents = file.read().decode('utf-8')
                    # חלק את תוכן הקובץ למשפטים (כל שורה היא משפט)
                    sentences = file_contents.split('\n')
                    # חשב את אורך המשפט הממוצע
                    sentence_lengths = [len(sentence.split()) for sentence in sentences]
                    avg_sentence_length = sum(sentence_lengths) / len(sentence_lengths)
                    # הוסף את אורך המשפט הממוצע לרשימה
                    avg_sentence_lengths.append((file_info.filename, avg_sentence_length))

# יצירת DataFrame מהרשימה
data_df = pd.DataFrame(avg_sentence_lengths, columns=['filename', 'avg_sentence_length'])

# יצירת קובץ Excel
wb = Workbook()
ws = wb.active

# כותרות העמודות
ws.append(['Filename', 'Avg Sentence Length'])

# הוספת הנתונים לגיליון אקסל
for row in avg_sentence_lengths:
    ws.append(row)

# שמירת הקובץ Excel
#excel_file_path = 'avg_sentence_lengths.xlsx'
excel_file_path = 'drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/avg_sentence_lengths.xlsx'


wb.save(excel_file_path)

print("Excel file created successfully.")

# הורדת הקובץ Excel
from google.colab import files
#files.download(excel_file_path)

import pandas as pd
import matplotlib.pyplot as plt

# קריאת הנתונים מקובץ ה-Excel
data_df = pd.read_excel('drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/long_average_sen/avg_sentence_lengths_Sean.xlsx')

# יצירת גרף scatter
plt.figure(figsize=(10, 6))
plt.scatter(data_df['age'], data_df['Avg Sentence Length'], color='blue', alpha=0.5)
plt.title('Sean: Avg Sentence Length vs. Age')
plt.xlabel('Age')
plt.ylabel('Avg Sentence Length')
plt.grid(True)
plt.show()

import zipfile
import os
import pandas as pd
from openpyxl import Workbook

# נתיב לקובץ ZIP
zip_path = 'drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/record_kids_data/data.zip'

# רשימה לשמירת נתוני אורך משפט ממוצע
avg_sentence_lengths = []

# פתח את קובץ הZIP
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    # עבור על כל קובץ בתוך הZIP
    for file_info in zip_ref.infolist():
        # בדוק אם הקובץ הוא קובץ טקסט
        #if file_info.filename.endswith('.cha'):
            # בדוק אם השם של הקובץ מכיל את המילים המבוקשות
            if 'finished' in file_info.filename and 'ComptonPater/Trevor' in file_info.filename:
                # קרא את תוכן הקובץ
                with zip_ref.open(file_info.filename) as file:
                    file_contents = file.read().decode('utf-8')
                    # חלק את תוכן הקובץ למשפטים (כל שורה היא משפט)
                    sentences = file_contents.split('\n')
                    # חשב את אורך המשפט הממוצע
                    sentence_lengths = [len(sentence.split()) for sentence in sentences]
                    avg_sentence_length = sum(sentence_lengths) / len(sentence_lengths)
                    # הוסף את אורך המשפט הממוצע לרשימה
                    avg_sentence_lengths.append((file_info.filename, avg_sentence_length))

# יצירת DataFrame מהרשימה
data_df = pd.DataFrame(avg_sentence_lengths, columns=['filename', 'avg_sentence_length'])

# יצירת קובץ Excel
wb = Workbook()
ws = wb.active

# כותרות העמודות
ws.append(['Filename', 'Avg Sentence Length'])

# הוספת הנתונים לגיליון אקסל
for row in avg_sentence_lengths:
    ws.append(row)

# שמירת הקובץ Excel
#excel_file_path = 'avg_sentence_lengths.xlsx'
excel_file_path = 'drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/avg_sentence_lengths.xlsx'


wb.save(excel_file_path)

print("Excel file created successfully.")

# הורדת הקובץ Excel
from google.colab import files
#files.download(excel_file_path)

import pandas as pd
import matplotlib.pyplot as plt

# קריאת הנתונים מקובץ ה-Excel
data_df = pd.read_excel('drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/long_average_sen/avg_sentence_lengths_Trevor.xlsx')

# יצירת גרף scatter
plt.figure(figsize=(10, 6))
plt.scatter(data_df['age'], data_df['Avg Sentence Length'], color='blue', alpha=0.5)
plt.title('Trevor: Avg Sentence Length vs. Age')
plt.xlabel('Age')
plt.ylabel('Avg Sentence Length')
plt.grid(True)
plt.show()

import zipfile
import os
import pandas as pd
from openpyxl import Workbook

# נתיב לקובץ ZIP
zip_path = 'drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/record_kids_data/data.zip'

# רשימה לשמירת נתוני אורך משפט ממוצע
avg_sentence_lengths = []

# פתח את קובץ הZIP
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    # עבור על כל קובץ בתוך הZIP
    for file_info in zip_ref.infolist():
        # בדוק אם הקובץ הוא קובץ טקסט
        #if file_info.filename.endswith('.cha'):
            # בדוק אם השם של הקובץ מכיל את המילים המבוקשות
            if 'finished' in file_info.filename and '/Goad/Julia/finished' in file_info.filename:
                # קרא את תוכן הקובץ
                with zip_ref.open(file_info.filename) as file:
                    file_contents = file.read().decode('utf-8')
                    # חלק את תוכן הקובץ למשפטים (כל שורה היא משפט)
                    sentences = file_contents.split('\n')
                    # חשב את אורך המשפט הממוצע
                    sentence_lengths = [len(sentence.split()) for sentence in sentences]
                    avg_sentence_length = sum(sentence_lengths) / len(sentence_lengths)
                    # הוסף את אורך המשפט הממוצע לרשימה
                    avg_sentence_lengths.append((file_info.filename, avg_sentence_length))

# יצירת DataFrame מהרשימה
data_df = pd.DataFrame(avg_sentence_lengths, columns=['filename', 'avg_sentence_length'])

# יצירת קובץ Excel
wb = Workbook()
ws = wb.active

# כותרות העמודות
ws.append(['Filename', 'Avg Sentence Length'])

# הוספת הנתונים לגיליון אקסל
for row in avg_sentence_lengths:
    ws.append(row)

# שמירת הקובץ Excel
#excel_file_path = 'avg_sentence_lengths.xlsx'
excel_file_path = 'drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/avg_sentence_lengths.xlsx'


wb.save(excel_file_path)

print("Excel file created successfully.")

# הורדת הקובץ Excel
from google.colab import files
#files.download(excel_file_path)

import pandas as pd
import matplotlib.pyplot as plt

# קריאת הנתונים מקובץ ה-Excel
data_df = pd.read_excel('drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/long_average_sen/avg_sentence_lengths_Julia_2.xlsx')

# יצירת גרף scatter
plt.figure(figsize=(10, 6))
plt.scatter(data_df['age'], data_df['Avg Sentence Length'], color='blue', alpha=0.5)
plt.title('Julia_2: Avg Sentence Length vs. Age')
plt.xlabel('Age')
plt.ylabel('Avg Sentence Length')
plt.grid(True)
plt.show()

import zipfile
import os
import pandas as pd
from openpyxl import Workbook

# נתיב לקובץ ZIP
zip_path = 'drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/record_kids_data/data.zip'

# רשימה לשמירת נתוני אורך משפט ממוצע
avg_sentence_lengths = []

# פתח את קובץ הZIP
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    # עבור על כל קובץ בתוך הZIP
    for file_info in zip_ref.infolist():
        # בדוק אם הקובץ הוא קובץ טקסט
        #if file_info.filename.endswith('.cha'):
            # בדוק אם השם של הקובץ מכיל את המילים המבוקשות
            if 'finished' in file_info.filename and '/Goad/Sonya/finished' in file_info.filename:
                # קרא את תוכן הקובץ
                with zip_ref.open(file_info.filename) as file:
                    file_contents = file.read().decode('utf-8')
                    # חלק את תוכן הקובץ למשפטים (כל שורה היא משפט)
                    sentences = file_contents.split('\n')
                    # חשב את אורך המשפט הממוצע
                    sentence_lengths = [len(sentence.split()) for sentence in sentences]
                    avg_sentence_length = sum(sentence_lengths) / len(sentence_lengths)
                    # הוסף את אורך המשפט הממוצע לרשימה
                    avg_sentence_lengths.append((file_info.filename, avg_sentence_length))

# יצירת DataFrame מהרשימה
data_df = pd.DataFrame(avg_sentence_lengths, columns=['filename', 'avg_sentence_length'])

# יצירת קובץ Excel
wb = Workbook()
ws = wb.active

# כותרות העמודות
ws.append(['Filename', 'Avg Sentence Length'])

# הוספת הנתונים לגיליון אקסל
for row in avg_sentence_lengths:
    ws.append(row)

# שמירת הקובץ Excel
#excel_file_path = 'avg_sentence_lengths.xlsx'
excel_file_path = 'drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/avg_sentence_lengths.xlsx'


wb.save(excel_file_path)

print("Excel file created successfully.")

# הורדת הקובץ Excel
from google.colab import files
#files.download(excel_file_path)

import pandas as pd
import matplotlib.pyplot as plt

# קריאת הנתונים מקובץ ה-Excel
data_df = pd.read_excel('drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/long_average_sen/avg_sentence_lengths_Sonya.xlsx')

# יצירת גרף scatter
plt.figure(figsize=(10, 6))
plt.scatter(data_df['age'], data_df['Avg Sentence Length'], color='blue', alpha=0.5)
plt.title('Sonya: Avg Sentence Length vs. Age')
plt.xlabel('Age')
plt.ylabel('Avg Sentence Length')
plt.grid(True)
plt.show()

import zipfile
import os
import pandas as pd
from openpyxl import Workbook

# נתיב לקובץ ZIP
zip_path = 'drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/record_kids_data/data.zip'

# רשימה לשמירת נתוני אורך משפט ממוצע
avg_sentence_lengths = []

# פתח את קובץ הZIP
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    # עבור על כל קובץ בתוך הZIP
    for file_info in zip_ref.infolist():
        # בדוק אם הקובץ הוא קובץ טקסט
        #if file_info.filename.endswith('.cha'):
            # בדוק אם השם של הקובץ מכיל את המילים המבוקשות
            if 'finished' in file_info.filename and 'Inkelas/E/finished' in file_info.filename:
                # קרא את תוכן הקובץ
                with zip_ref.open(file_info.filename) as file:
                    file_contents = file.read().decode('utf-8')
                    # חלק את תוכן הקובץ למשפטים (כל שורה היא משפט)
                    sentences = file_contents.split('\n')
                    # חשב את אורך המשפט הממוצע
                    sentence_lengths = [len(sentence.split()) for sentence in sentences]
                    avg_sentence_length = sum(sentence_lengths) / len(sentence_lengths)
                    # הוסף את אורך המשפט הממוצע לרשימה
                    avg_sentence_lengths.append((file_info.filename, avg_sentence_length))

# יצירת DataFrame מהרשימה
data_df = pd.DataFrame(avg_sentence_lengths, columns=['filename', 'avg_sentence_length'])

# יצירת קובץ Excel
wb = Workbook()
ws = wb.active

# כותרות העמודות
ws.append(['Filename', 'Avg Sentence Length'])

# הוספת הנתונים לגיליון אקסל
for row in avg_sentence_lengths:
    ws.append(row)

# שמירת הקובץ Excel
#excel_file_path = 'avg_sentence_lengths.xlsx'
excel_file_path = 'drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/avg_sentence_lengths.xlsx'


wb.save(excel_file_path)

print("Excel file created successfully.")

# הורדת הקובץ Excel
from google.colab import files
#files.download(excel_file_path)

import pandas as pd
import matplotlib.pyplot as plt

# קריאת הנתונים מקובץ ה-Excel
data_df = pd.read_excel('drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/long_average_sen/avg_sentence_lengths_Inkelas.xlsx')

# יצירת גרף scatter
plt.figure(figsize=(10, 6))
plt.scatter(data_df['age'], data_df['Avg Sentence Length'], color='blue', alpha=0.5)
plt.title('Inkelas: Avg Sentence Length vs. Age')
plt.xlabel('Age')
plt.ylabel('Avg Sentence Length')
plt.grid(True)
plt.show()

import zipfile
import os
import pandas as pd
from openpyxl import Workbook

# נתיב לקובץ ZIP
zip_path = 'drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/record_kids_data/data.zip'

# רשימה לשמירת נתוני אורך משפט ממוצע
avg_sentence_lengths = []

# פתח את קובץ הZIP
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    # עבור על כל קובץ בתוך הZIP
    for file_info in zip_ref.infolist():
        # בדוק אם הקובץ הוא קובץ טקסט
        #if file_info.filename.endswith('.cha'):
            # בדוק אם השם של הקובץ מכיל את המילים המבוקשות
            if 'finished' in file_info.filename and '/Providence/Alex/finished' in file_info.filename:
                # קרא את תוכן הקובץ
                with zip_ref.open(file_info.filename) as file:
                    file_contents = file.read().decode('utf-8')
                    # חלק את תוכן הקובץ למשפטים (כל שורה היא משפט)
                    sentences = file_contents.split('\n')
                    # חשב את אורך המשפט הממוצע
                    sentence_lengths = [len(sentence.split()) for sentence in sentences]
                    avg_sentence_length = sum(sentence_lengths) / len(sentence_lengths)
                    # הוסף את אורך המשפט הממוצע לרשימה
                    avg_sentence_lengths.append((file_info.filename, avg_sentence_length))

# יצירת DataFrame מהרשימה
data_df = pd.DataFrame(avg_sentence_lengths, columns=['filename', 'avg_sentence_length'])

# יצירת קובץ Excel
wb = Workbook()
ws = wb.active

# כותרות העמודות
ws.append(['Filename', 'Avg Sentence Length'])

# הוספת הנתונים לגיליון אקסל
for row in avg_sentence_lengths:
    ws.append(row)

# שמירת הקובץ Excel
#excel_file_path = 'avg_sentence_lengths.xlsx'
excel_file_path = 'drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/avg_sentence_lengths.xlsx'


wb.save(excel_file_path)

print("Excel file created successfully.")

# הורדת הקובץ Excel
from google.colab import files
#files.download(excel_file_path)

import pandas as pd
import matplotlib.pyplot as plt

# קריאת הנתונים מקובץ ה-Excel
data_df = pd.read_excel('drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/long_average_sen/avg_sentence_lengths_Alex.xlsx')

# יצירת גרף scatter
plt.figure(figsize=(10, 6))
plt.scatter(data_df['age'], data_df['Avg Sentence Length'], color='blue', alpha=0.5)
plt.title('Alex: Avg Sentence Length vs. Age')
plt.xlabel('Age')
plt.ylabel('Avg Sentence Length')
plt.grid(True)
plt.show()

import zipfile
import os
import pandas as pd
from openpyxl import Workbook

# נתיב לקובץ ZIP
zip_path = 'drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/record_kids_data/data.zip'

# רשימה לשמירת נתוני אורך משפט ממוצע
avg_sentence_lengths = []

# פתח את קובץ הZIP
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    # עבור על כל קובץ בתוך הZIP
    for file_info in zip_ref.infolist():
        # בדוק אם הקובץ הוא קובץ טקסט
        #if file_info.filename.endswith('.cha'):
            # בדוק אם השם של הקובץ מכיל את המילים המבוקשות
            if 'finished' in file_info.filename and '/Providence/Ethan/finished' in file_info.filename:
                # קרא את תוכן הקובץ
                with zip_ref.open(file_info.filename) as file:
                    file_contents = file.read().decode('utf-8')
                    # חלק את תוכן הקובץ למשפטים (כל שורה היא משפט)
                    sentences = file_contents.split('\n')
                    # חשב את אורך המשפט הממוצע
                    sentence_lengths = [len(sentence.split()) for sentence in sentences]
                    avg_sentence_length = sum(sentence_lengths) / len(sentence_lengths)
                    # הוסף את אורך המשפט הממוצע לרשימה
                    avg_sentence_lengths.append((file_info.filename, avg_sentence_length))

# יצירת DataFrame מהרשימה
data_df = pd.DataFrame(avg_sentence_lengths, columns=['filename', 'avg_sentence_length'])

# יצירת קובץ Excel
wb = Workbook()
ws = wb.active

# כותרות העמודות
ws.append(['Filename', 'Avg Sentence Length'])

# הוספת הנתונים לגיליון אקסל
for row in avg_sentence_lengths:
    ws.append(row)

# שמירת הקובץ Excel
#excel_file_path = 'avg_sentence_lengths.xlsx'
excel_file_path = 'drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/avg_sentence_lengths.xlsx'


wb.save(excel_file_path)

print("Excel file created successfully.")

# הורדת הקובץ Excel
from google.colab import files
#files.download(excel_file_path)

import pandas as pd
import matplotlib.pyplot as plt

# קריאת הנתונים מקובץ ה-Excel
data_df = pd.read_excel('drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/long_average_sen/avg_sentence_lengths_Ethan.xlsx')

# יצירת גרף scatter
plt.figure(figsize=(10, 6))
plt.scatter(data_df['age'], data_df['Avg Sentence Length'], color='blue', alpha=0.5)
plt.title('Ethan: Avg Sentence Length vs. Age')
plt.xlabel('Age')
plt.ylabel('Avg Sentence Length')
plt.grid(True)
plt.show()

import zipfile
import os
import pandas as pd
from openpyxl import Workbook

# נתיב לקובץ ZIP
zip_path = 'drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/record_kids_data/data.zip'

# רשימה לשמירת נתוני אורך משפט ממוצע
avg_sentence_lengths = []

# פתח את קובץ הZIP
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    # עבור על כל קובץ בתוך הZIP
    for file_info in zip_ref.infolist():
        # בדוק אם הקובץ הוא קובץ טקסט
        #if file_info.filename.endswith('.cha'):
            # בדוק אם השם של הקובץ מכיל את המילים המבוקשות
            if 'finished' in file_info.filename and '/Providence/Lily/finished' in file_info.filename:
                # קרא את תוכן הקובץ
                with zip_ref.open(file_info.filename) as file:
                    file_contents = file.read().decode('utf-8')
                    # חלק את תוכן הקובץ למשפטים (כל שורה היא משפט)
                    sentences = file_contents.split('\n')
                    # חשב את אורך המשפט הממוצע
                    sentence_lengths = [len(sentence.split()) for sentence in sentences]
                    avg_sentence_length = sum(sentence_lengths) / len(sentence_lengths)
                    # הוסף את אורך המשפט הממוצע לרשימה
                    avg_sentence_lengths.append((file_info.filename, avg_sentence_length))

# יצירת DataFrame מהרשימה
data_df = pd.DataFrame(avg_sentence_lengths, columns=['filename', 'avg_sentence_length'])

# יצירת קובץ Excel
wb = Workbook()
ws = wb.active

# כותרות העמודות
ws.append(['Filename', 'Avg Sentence Length'])

# הוספת הנתונים לגיליון אקסל
for row in avg_sentence_lengths:
    ws.append(row)

# שמירת הקובץ Excel
#excel_file_path = 'avg_sentence_lengths.xlsx'
excel_file_path = 'drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/avg_sentence_lengths.xlsx'


wb.save(excel_file_path)

print("Excel file created successfully.")

# הורדת הקובץ Excel
from google.colab import files
#files.download(excel_file_path)

import pandas as pd
import matplotlib.pyplot as plt

# קריאת הנתונים מקובץ ה-Excel
data_df = pd.read_excel('drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/long_average_sen/avg_sentence_lengths_Lily.xlsx')

# יצירת גרף scatter
plt.figure(figsize=(10, 6))
plt.scatter(data_df['age'], data_df['Avg Sentence Length'], color='blue', alpha=0.5)
plt.title('Lily: Avg Sentence Length vs. Age')
plt.xlabel('Age')
plt.ylabel('Avg Sentence Length')
plt.grid(True)
plt.show()

import zipfile
import os
import pandas as pd
from openpyxl import Workbook

# נתיב לקובץ ZIP
zip_path = 'drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/record_kids_data/data.zip'

# רשימה לשמירת נתוני אורך משפט ממוצע
avg_sentence_lengths = []

# פתח את קובץ הZIP
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    # עבור על כל קובץ בתוך הZIP
    for file_info in zip_ref.infolist():
        # בדוק אם הקובץ הוא קובץ טקסט
        #if file_info.filename.endswith('.cha'):
            # בדוק אם השם של הקובץ מכיל את המילים המבוקשות
            if 'finished' in file_info.filename and '/Providence/Violet/finished' in file_info.filename:
                # קרא את תוכן הקובץ
                with zip_ref.open(file_info.filename) as file:
                    file_contents = file.read().decode('utf-8')
                    # חלק את תוכן הקובץ למשפטים (כל שורה היא משפט)
                    sentences = file_contents.split('\n')
                    # חשב את אורך המשפט הממוצע
                    sentence_lengths = [len(sentence.split()) for sentence in sentences]
                    avg_sentence_length = sum(sentence_lengths) / len(sentence_lengths)
                    # הוסף את אורך המשפט הממוצע לרשימה
                    avg_sentence_lengths.append((file_info.filename, avg_sentence_length))

# יצירת DataFrame מהרשימה
data_df = pd.DataFrame(avg_sentence_lengths, columns=['filename', 'avg_sentence_length'])

# יצירת קובץ Excel
wb = Workbook()
ws = wb.active

# כותרות העמודות
ws.append(['Filename', 'Avg Sentence Length'])

# הוספת הנתונים לגיליון אקסל
for row in avg_sentence_lengths:
    ws.append(row)

# שמירת הקובץ Excel
#excel_file_path = 'avg_sentence_lengths.xlsx'
excel_file_path = 'drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/avg_sentence_lengths.xlsx'


wb.save(excel_file_path)

print("Excel file created successfully.")

# הורדת הקובץ Excel
from google.colab import files
#files.download(excel_file_path)

import pandas as pd
import matplotlib.pyplot as plt

# קריאת הנתונים מקובץ ה-Excel
data_df = pd.read_excel('drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/long_average_sen/avg_sentence_lengths_Violet.xlsx')

# יצירת גרף scatter
plt.figure(figsize=(10, 6))
plt.scatter(data_df['age'], data_df['Avg Sentence Length'], color='blue', alpha=0.5)
plt.title('Violet: Avg Sentence Length vs. Age')
plt.xlabel('Age')
plt.ylabel('Avg Sentence Length')
plt.grid(True)
plt.show()

import zipfile
import os
import pandas as pd
from openpyxl import Workbook

# נתיב לקובץ ZIP
zip_path = 'drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/record_kids_data/data.zip'

# רשימה לשמירת נתוני אורך משפט ממוצע
avg_sentence_lengths = []

# פתח את קובץ הZIP
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    # עבור על כל קובץ בתוך הZIP
    for file_info in zip_ref.infolist():
        # בדוק אם הקובץ הוא קובץ טקסט
        #if file_info.filename.endswith('.cha'):
            # בדוק אם השם של הקובץ מכיל את המילים המבוקשות
            if 'finished' in file_info.filename and '/Providence/William/finished' in file_info.filename:
                # קרא את תוכן הקובץ
                with zip_ref.open(file_info.filename) as file:
                    file_contents = file.read().decode('utf-8')
                    # חלק את תוכן הקובץ למשפטים (כל שורה היא משפט)
                    sentences = file_contents.split('\n')
                    # חשב את אורך המשפט הממוצע
                    sentence_lengths = [len(sentence.split()) for sentence in sentences]
                    avg_sentence_length = sum(sentence_lengths) / len(sentence_lengths)
                    # הוסף את אורך המשפט הממוצע לרשימה
                    avg_sentence_lengths.append((file_info.filename, avg_sentence_length))

# יצירת DataFrame מהרשימה
data_df = pd.DataFrame(avg_sentence_lengths, columns=['filename', 'avg_sentence_length'])

# יצירת קובץ Excel
wb = Workbook()
ws = wb.active

# כותרות העמודות
ws.append(['Filename', 'Avg Sentence Length'])

# הוספת הנתונים לגיליון אקסל
for row in avg_sentence_lengths:
    ws.append(row)

# שמירת הקובץ Excel
#excel_file_path = 'avg_sentence_lengths.xlsx'
excel_file_path = 'drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/avg_sentence_lengths.xlsx'


wb.save(excel_file_path)

print("Excel file created successfully.")

# הורדת הקובץ Excel
from google.colab import files
#files.download(excel_file_path)

import pandas as pd
import matplotlib.pyplot as plt

# קריאת הנתונים מקובץ ה-Excel
data_df = pd.read_excel('drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/long_average_sen/avg_sentence_lengths_William.xlsx')

# יצירת גרף scatter
plt.figure(figsize=(10, 6))
plt.scatter(data_df['age'], data_df['Avg Sentence Length'], color='blue', alpha=0.5)
plt.title('William: Avg Sentence Length vs. Age')
plt.xlabel('Age')
plt.ylabel('Avg Sentence Length')
plt.grid(True)
plt.show()



import zipfile
import os
import pandas as pd
from openpyxl import Workbook

# נתיב לקובץ ZIP
zip_path = 'drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/record_kids_data/data.zip'

# רשימה לשמירת נתוני אורך משפט ממוצע
avg_sentence_lengths = []

# פתח את קובץ הZIP
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    # עבור על כל קובץ בתוך הZIP
    for file_info in zip_ref.infolist():
        # בדוק אם הקובץ הוא קובץ טקסט
        #if file_info.filename.endswith('.cha'):
            # בדוק אם השם של הקובץ מכיל את המילים המבוקשות
            if 'finished' in file_info.filename and 'Sachs/finished' in file_info.filename:
                # קרא את תוכן הקובץ
                with zip_ref.open(file_info.filename) as file:
                    file_contents = file.read().decode('utf-8')
                    # חלק את תוכן הקובץ למשפטים (כל שורה היא משפט)
                    sentences = file_contents.split('\n')
                    # חשב את אורך המשפט הממוצע
                    sentence_lengths = [len(sentence.split()) for sentence in sentences]
                    avg_sentence_length = sum(sentence_lengths) / len(sentence_lengths)
                    # הוסף את אורך המשפט הממוצע לרשימה
                    avg_sentence_lengths.append((file_info.filename, avg_sentence_length))

# יצירת DataFrame מהרשימה
data_df = pd.DataFrame(avg_sentence_lengths, columns=['filename', 'avg_sentence_length'])

# יצירת קובץ Excel
wb = Workbook()
ws = wb.active

# כותרות העמודות
ws.append(['Filename', 'Avg Sentence Length'])

# הוספת הנתונים לגיליון אקסל
for row in avg_sentence_lengths:
    ws.append(row)

# שמירת הקובץ Excel
#excel_file_path = 'avg_sentence_lengths.xlsx'
excel_file_path = 'drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/avg_sentence_lengths.xlsx'


wb.save(excel_file_path)

print("Excel file created successfully.")

# הורדת הקובץ Excel
from google.colab import files
#files.download(excel_file_path)

import pandas as pd
import matplotlib.pyplot as plt

# קריאת הנתונים מקובץ ה-Excel
data_df = pd.read_excel('drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/long_average_sen/avg_sentence_lengths_Sachs.xlsx')

# יצירת גרף scatter
plt.figure(figsize=(10, 6))
plt.scatter(data_df['age'], data_df['Avg Sentence Length'], color='blue', alpha=0.5)
plt.title('Sachs: Avg Sentence Length vs. Age')
plt.xlabel('Age')
plt.ylabel('Avg Sentence Length')
plt.grid(True)
plt.show()

import zipfile
import os
import pandas as pd
from openpyxl import Workbook

# נתיב לקובץ ZIP
zip_path = 'drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/record_kids_data/data.zip'

# רשימה לשמירת נתוני אורך משפט ממוצע
avg_sentence_lengths = []

# פתח את קובץ הZIP
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    # עבור על כל קובץ בתוך הZIP
    for file_info in zip_ref.infolist():
        # בדוק אם הקובץ הוא קובץ טקסט
        #if file_info.filename.endswith('.cha'):
            # בדוק אם השם של הקובץ מכיל את המילים המבוקשות
            if 'finished' in file_info.filename and 'Suppes/finished' in file_info.filename:
                # קרא את תוכן הקובץ
                with zip_ref.open(file_info.filename) as file:
                    file_contents = file.read().decode('utf-8')
                    # חלק את תוכן הקובץ למשפטים (כל שורה היא משפט)
                    sentences = file_contents.split('\n')
                    # חשב את אורך המשפט הממוצע
                    sentence_lengths = [len(sentence.split()) for sentence in sentences]
                    avg_sentence_length = sum(sentence_lengths) / len(sentence_lengths)
                    # הוסף את אורך המשפט הממוצע לרשימה
                    avg_sentence_lengths.append((file_info.filename, avg_sentence_length))

# יצירת DataFrame מהרשימה
data_df = pd.DataFrame(avg_sentence_lengths, columns=['filename', 'avg_sentence_length'])

# יצירת קובץ Excel
wb = Workbook()
ws = wb.active

# כותרות העמודות
ws.append(['Filename', 'Avg Sentence Length'])

# הוספת הנתונים לגיליון אקסל
for row in avg_sentence_lengths:
    ws.append(row)

# שמירת הקובץ Excel
#excel_file_path = 'avg_sentence_lengths.xlsx'
excel_file_path = 'drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/avg_sentence_lengths.xlsx'


wb.save(excel_file_path)

print("Excel file created successfully.")

# הורדת הקובץ Excel
from google.colab import files
#files.download(excel_file_path)

import pandas as pd
import matplotlib.pyplot as plt

# קריאת הנתונים מקובץ ה-Excel
data_df = pd.read_excel('drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/long_average_sen/avg_sentence_lengths_Suppes.xlsx')

# יצירת גרף scatter
plt.figure(figsize=(10, 6))
plt.scatter(data_df['age'], data_df['Avg Sentence Length'], color='blue', alpha=0.5)
plt.title('Suppes: Avg Sentence Length vs. Age')
plt.xlabel('Age')
plt.ylabel('Avg Sentence Length')
plt.grid(True)
plt.show()

import zipfile
import os
import pandas as pd
from openpyxl import Workbook

# נתיב לקובץ ZIP
zip_path = 'drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/record_kids_data/data.zip'

# רשימה לשמירת נתוני אורך משפט ממוצע
avg_sentence_lengths = []

# פתח את קובץ הZIP
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    # עבור על כל קובץ בתוך הZIP
    for file_info in zip_ref.infolist():
        # בדוק אם הקובץ הוא קובץ טקסט
        #if file_info.filename.endswith('.cha'):
            # בדוק אם השם של הקובץ מכיל את המילים המבוקשות
            if 'finished' in file_info.filename and '/Providence/Naima/finished' in file_info.filename:
                # קרא את תוכן הקובץ
                with zip_ref.open(file_info.filename) as file:
                    file_contents = file.read().decode('utf-8')
                    # חלק את תוכן הקובץ למשפטים (כל שורה היא משפט)
                    sentences = file_contents.split('\n')
                    # חשב את אורך המשפט הממוצע
                    sentence_lengths = [len(sentence.split()) for sentence in sentences]
                    avg_sentence_length = sum(sentence_lengths) / len(sentence_lengths)
                    # הוסף את אורך המשפט הממוצע לרשימה
                    avg_sentence_lengths.append((file_info.filename, avg_sentence_length))

# יצירת DataFrame מהרשימה
data_df = pd.DataFrame(avg_sentence_lengths, columns=['filename', 'avg_sentence_length'])

# יצירת קובץ Excel
wb = Workbook()
ws = wb.active

# כותרות העמודות
ws.append(['Filename', 'Avg Sentence Length'])

# הוספת הנתונים לגיליון אקסל
for row in avg_sentence_lengths:
    ws.append(row)

# שמירת הקובץ Excel
#excel_file_path = 'avg_sentence_lengths.xlsx'
excel_file_path = 'drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/avg_sentence_lengths.xlsx'


wb.save(excel_file_path)

print("Excel file created successfully.")

# הורדת הקובץ Excel
from google.colab import files
#files.download(excel_file_path)

import pandas as pd
import matplotlib.pyplot as plt

# קריאת הנתונים מקובץ ה-Excel
data_df = pd.read_excel('drive/MyDrive/bioinformatica/Colab_Notebooks/final_project/basic_analayze_data/long_average_sen/avg_sentence_lengths_Naima.xlsx')

# יצירת גרף scatter
plt.figure(figsize=(10, 6))
plt.scatter(data_df['age'], data_df['Avg Sentence Length'], color='blue', alpha=0.5)
plt.title('Naima: Avg Sentence Length vs. Age')
plt.xlabel('Age')
plt.ylabel('Avg Sentence Length')
plt.grid(True)
plt.show()
