# -*- coding: utf-8 -*-
"""NLP_learn_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_uZabwgA5wGMLMAUc6CPM6fsKlF2FT_P
"""

from transformers import pipeline

# יצירת מודל של MASK filling
unmasker = pipeline("fill-mask", model="bert-base-uncased")

# המשפט עם תווים MASK למילים שאתה רוצה למלא
sentence = "I love my [MASK]."

# הפעלת המודל על המשפט כדי למלא את התווים MASK
result = unmasker(sentence)

# הדפסת התוצאה
print(result)

from transformers import pipeline

classifier = pipeline("sentiment-analysis")


classifier(
    ["I've been waiting for a HuggingFace course my whole life.", "I hate this so much!","I kove ny family","I hate you"])

from transformers import GPT2LMHeadModel, GPT2Tokenizer

class GPT2_Model:
    def __init__(self):
        self.tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
        self.model = GPT2LMHeadModel.from_pretrained("gpt2")

    def generate_text(self, prompt, max_length=50, temperature=0.7):
        input_ids = self.tokenizer.encode(prompt, return_tensors="pt")
        output = self.model.generate(input_ids, max_length=max_length, temperature=temperature)
        return self.tokenizer.decode(output[0], skip_special_tokens=True)


gpt2_instance = GPT2_Model()
generated_text = gpt2_instance.generate_text("Your prompt here", max_length=100, temperature=0.9)
print(generated_text)